CREATE TABLE [dbo].[AccountEmployeeCharts] (
    [AccountChartId]          UNIQUEIDENTIFIER CONSTRAINT [DF_AccountEmployeeChartCustomization_AccountChartId] DEFAULT (newid()) NOT NULL,
    [SystemChartTypeId]       UNIQUEIDENTIFIER NOT NULL,
    [AccountId]               INT              NOT NULL,
    [AccountEmployeeId]       INT              NOT NULL,
    [CreatedOn]               DATETIME         NULL,
    [CreatedByEmployeeId]     INT              NULL,
    [ModifiedOn]              DATETIME         NULL,
    [ModifiedByEmployeeId]    INT              NULL,
    [SystemChartId]           UNIQUEIDENTIFIER NOT NULL,
    [IsCollectPieSlices]      BIT              NULL,
    [CollectedThreshold]      INT              NULL,
    [CollectedColor]          NVARCHAR (100)   NULL,
    [CollectedLabel]          NVARCHAR (100)   NULL,
    [CollectedLegendText]     NVARCHAR (100)   NULL,
    [IsShowExploded]          BIT              NULL,
    [AccountChartName]        NVARCHAR (100)   NULL,
    [IsShowLegend]            BIT              NULL,
    [IsShowas3D]              BIT              NULL,
    [DoughnutRadius]          INT              NULL,
    [DrawingStyle]            NVARCHAR (100)   NULL,
    [LabelStyle]              NVARCHAR (100)   NULL,
    [PointWidth]              FLOAT (53)       NULL,
    [RotationAngle]           INT              NULL,
    [PointsGap]               INT              NULL,
    [LabelsPlacement]         VARCHAR (100)    NULL,
    [MinPointHeight]          INT              NULL,
    [StandardPalette]         NVARCHAR (100)   NULL,
    [CustomPalette]           NVARCHAR (100)   NULL,
    [IsHideSupplementalChart] BIT              NULL,
    [CollectedPercentage]     INT              NULL,
    [SupplementalChartSize]   NVARCHAR (100)   NULL,
    [IsCollectSmallSegments]  BIT              NULL,
    CONSTRAINT [PK_AccountEmployeeChartCustomization] PRIMARY KEY CLUSTERED ([AccountChartId] ASC)
);

