CREATE TABLE [dbo].[AccountEmployeeTimeOffAudit] (
    [AccountEmployeeTimeOffAuditId] UNIQUEIDENTIFIER CONSTRAINT [DF_AccountEmployeeTimeOffAudit_AccountEmployeeTimeOffAuditId] DEFAULT (newid()) NOT NULL,
    [AccountTimeOffTypeId]          UNIQUEIDENTIFIER NOT NULL,
    [AccountTimeOffPolicyId]        UNIQUEIDENTIFIER NULL,
    [SystemEarnPeriodId]            UNIQUEIDENTIFIER NULL,
    [SystemResetToZeroTypeId]       UNIQUEIDENTIFIER NULL,
    [AccountEmployeeId]             INT              NOT NULL,
    [AccountId]                     INT              NOT NULL,
    [CreatedByEmployeeId]           INT              NULL,
    [ModifiedByEmployeeId]          INT              NULL,
    [EffectiveDate]                 DATETIME         NULL,
    [Earned]                        FLOAT (53)       NULL,
    [Consume]                       FLOAT (53)       NULL,
    [Available]                     FLOAT (53)       NULL,
    [CarryForward]                  FLOAT (53)       NULL,
    [ResetToHours]                  FLOAT (53)       NULL,
    [EarnHours]                     FLOAT (53)       NULL,
    [MaximumAvailable]              FLOAT (53)       NULL,
    [InitialSetToHours]             FLOAT (53)       NULL,
    [AccountTimeOffType]            NVARCHAR (100)   NULL,
    [LastEarnedDate]                DATETIME         NULL,
    [LastResetDate]                 DATETIME         NULL,
    [AccountTimeOffPolicy]          NVARCHAR (250)   NULL,
    [SortOrder]                     INT              IDENTITY (1, 1) NOT NULL,
    [PolicyExecutedDate]            DATETIME         NOT NULL,
    [CreatedOn]                     DATETIME         NULL,
    [ModifiedOn]                    DATETIME         NULL,
    [PolicyEarnResetAutidAction]    NVARCHAR (250)   NULL,
    [PolicyExecutionType]           NVARCHAR (250)   NULL,
    [AuditSource]                   NVARCHAR (250)   NULL,
    [SystemEarnPeriod]              NVARCHAR (100)   NULL,
    [SystemResetToZeroType]         NVARCHAR (100)   NULL,
    [BeforeAfterPolicyChange]       NVARCHAR (50)    NULL,
    CONSTRAINT [PK_AccountEmployeeTimeOffAudit] PRIMARY KEY CLUSTERED ([AccountEmployeeTimeOffAuditId] ASC)
);

