CREATE TABLE [dbo].[accountproject_bkp_20160923_rmdm] (
    [AccountProjectId]         INT             IDENTITY (1, 1) NOT NULL,
    [AccountId]                INT             NOT NULL,
    [AccountProjectTypeId]     INT             NOT NULL,
    [AccountClientId]          INT             NOT NULL,
    [ProjectBillingTypeId]     INT             NULL,
    [ProjectName]              NVARCHAR (100)  NOT NULL,
    [ProjectDescription]       NVARCHAR (4000) NOT NULL,
    [StartDate]                SMALLDATETIME   NULL,
    [AccountMilestoneId]       INT             NOT NULL,
    [Deadline]                 SMALLDATETIME   NULL,
    [LeaderEmployeeId]         INT             NULL,
    [ProjectManagerEmployeeId] INT             NOT NULL,
    [EstimatedTime]            SMALLDATETIME   NULL,
    [EstimatedDuration]        FLOAT (53)      NULL,
    [EstimatedDurationUnit]    NVARCHAR (20)   NULL,
    [ProjectCode]              NVARCHAR (100)  NULL,
    [DefaultBillingRate]       MONEY           NULL,
    [IsActive]                 BIT             NOT NULL,
    [ProjectStatusId]          INT             NOT NULL,
    [AccountPriorityId]        INT             NULL,
    [TimeSheetApprovalTypeId]  INT             NULL,
    [ExpenseApprovalTypeId]    INT             NULL,
    [CreatedOn]                DATETIME        NOT NULL,
    [CreatedByEmployeeId]      INT             NOT NULL,
    [ModifiedOn]               DATETIME        NOT NULL,
    [ModifiedByEmployeeId]     INT             NOT NULL,
    [ProjectBillingRateTypeId] INT             NULL,
    [AccountPartyContactId]    INT             NULL,
    [AccountPartyDepartmentId] INT             NULL,
    [IsDisabled]               BIT             NOT NULL,
    [IsTemplate]               BIT             NOT NULL,
    [IsProject]                BIT             NOT NULL,
    [AccountProjectTemplateId] INT             NULL,
    [Completed]                BIT             NOT NULL,
    [IsDeleted]                BIT             NULL,
    [CustomField1]             NVARCHAR (2000) NULL,
    [CustomField2]             NVARCHAR (2000) NULL,
    [CustomField3]             NVARCHAR (2000) NULL,
    [CustomField4]             NVARCHAR (2000) NULL,
    [CustomField5]             NVARCHAR (2000) NULL,
    [CustomField6]             NVARCHAR (2000) NULL,
    [CustomField7]             NVARCHAR (2000) NULL,
    [CustomField8]             NVARCHAR (2000) NULL,
    [CustomField9]             NVARCHAR (2000) NULL,
    [CustomField10]            NVARCHAR (2000) NULL,
    [CustomField11]            NVARCHAR (2000) NULL,
    [CustomField12]            NVARCHAR (2000) NULL,
    [CustomField13]            NVARCHAR (2000) NULL,
    [CustomField14]            NVARCHAR (2000) NULL,
    [CustomField15]            NVARCHAR (2000) NULL,
    [ProjectPrefix]            NVARCHAR (100)  NULL,
    [IsForAllClientProject]    BIT             NULL,
    [ProjectEstimatedCost]     FLOAT (53)      NULL,
    [FixedCost]                FLOAT (53)      NULL
);

