CREATE TABLE [dbo].[apt_back] (
    [AccountProjectTaskId]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [AccountProjectId]             INT            NOT NULL,
    [ParentAccountProjectTaskId]   BIGINT         NULL,
    [TaskName]                     NVARCHAR (200) NOT NULL,
    [TaskDescription]              NVARCHAR (MAX) NOT NULL,
    [AccountTaskTypeId]            INT            NOT NULL,
    [Duration]                     INT            NULL,
    [DurationUnit]                 NVARCHAR (20)  NULL,
    [DeadlineDate]                 SMALLDATETIME  NULL,
    [CompletedPercent]             TINYINT        NULL,
    [Completed]                    BIT            NOT NULL,
    [IsParentTask]                 BIT            NULL,
    [IsForAllEmployees]            BIT            NULL,
    [AccountPriorityId]            INT            NOT NULL,
    [TaskStatusId]                 INT            NULL,
    [AccountProjectMilestoneId]    BIGINT         NOT NULL,
    [IsReOpen]                     BIT            NOT NULL,
    [CreatedOn]                    DATETIME       NULL,
    [CreatedByEmployeeId]          INT            NULL,
    [ModifiedOn]                   DATETIME       NULL,
    [ModifiedByEmployeeId]         INT            NULL,
    [EstimatedCost]                FLOAT (53)     NULL,
    [EstimatedTimeSpent]           FLOAT (53)     NULL,
    [EstimatedTimeSpentUnit]       NVARCHAR (20)  NULL,
    [IsBillable]                   BIT            NULL,
    [IsDisabled]                   BIT            NOT NULL,
    [AccountBillingRateId]         INT            NULL,
    [IsForAllProjectTask]          BIT            NULL,
    [TaskCode]                     NVARCHAR (30)  NULL,
    [AccountProjectTaskTemplateId] INT            NULL
);

