
CREATE VIEW dbo.rptvueAccountEmployeeTimeEntry
AS
SELECT     dbo.vueAccountEmployeeTimeEntryForReport.EmployeeName
, dbo.vueAccountEmployeeTimeEntryForReport.ProjectName, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskName, dbo.vueAccountEmployeeTimeEntryForReport.TotalTime, 
                      dbo.vueAccountEmployeeTimeEntryForReport.Approved, dbo.vueAccountEmployeeTimeEntryForReport.AccountEmployeeId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AccountProjectId, dbo.vueAccountEmployeeTimeEntryForReport.TeamLeadApproved, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectManagerApproved, dbo.vueAccountEmployeeTimeEntryForReport.AdministratorApproved, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AccountEmployeeTimeEntryId, dbo.vueAccountEmployeeTimeEntryForReport.StartTime, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EndTime, dbo.vueAccountEmployeeTimeEntryForReport.TimeEntryDate, 
                      dbo.vueAccountEmployeeTimeEntryForReport.Description, 
				  dbo.vueAccountEmployeeTimeEntryForReport.AccountId ,
                      dbo.vueAccountEmployeeTimeEntryForReport.TotalMinutes, dbo.vueAccountEmployeeTimeEntryForReport.WeekDay, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientName, dbo.vueAccountEmployeeTimeEntryForReport.AccountProjectTaskId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.BillingType, dbo.vueAccountEmployeeTimeEntryForReport.LeaderEmployeeId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectManagerEmployeeId, dbo.vueAccountEmployeeTimeEntryForReport.TimeSheetApprovalTypeId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ExpenseApprovalTypeId, dbo.vueAccountEmployeeTimeEntryForReport.IsBillable, 
                      dbo.vueAccountEmployeeTimeEntryForReport.Rejected, dbo.vueAccountEmployeeTimeEntryForReport.BillingRate, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectBillingRateTypeId, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCode, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AccountDepartmentId, dbo.vueAccountEmployeeTimeEntryForReport.DepartmentName, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EstimatedCost, dbo.vueAccountEmployeeTimeEntryForReport.EstimatedHours, 
                      dbo.vueAccountEmployeeTimeEntryForReport.Submitted, dbo.vueAccountEmployeeTimeEntryForReport.AccountWorkType, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EMailAddress, dbo.vueAccountEmployeeTimeEntryForReport.AccountLocation, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AccountCostCenter, dbo.vueAccountEmployeeTimeEntryForReport.AccountCostCenterCode, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AccountWorkTypeCode, dbo.vueAccountEmployeeTimeEntryForReport.ProjectCode, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskCode, dbo.vueAccountEmployeeTimeEntryForReport.AccountLocationId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ApproverComments, 
					  dbo.vueAccountEmployeeTimeEntryForReport.Amount, 
                      dbo.vueAccountEmployeeTimeEntryForReport.BillingRateCurrencyId, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeRateCurrencyId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.BillingRateExchangeRate, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeRateExchangeRate, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AccountBaseCurrencyId, dbo.vueAccountEmployeeTimeEntryForReport.BillingRateCurrencyCode, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AmountCurrencyCode,
					   CASE WHEN vueAccountEmployeeTimeEntryForReport.Submitted = 1 AND 
                      vueAccountEmployeeTimeEntryForReport.Approved = 0 THEN 'Submitted' WHEN vueAccountEmployeeTimeEntryForReport.Approved = 1 THEN 'Approved' WHEN vueAccountEmployeeTimeEntryForReport.Rejected
                       = 1 THEN 'Rejected' WHEN vueAccountEmployeeTimeEntryForReport.Submitted = 0 AND vueAccountEmployeeTimeEntryForReport.Approved = 0 AND 
                      vueAccountEmployeeTimeEntryForReport.Rejected = 0 THEN 'Not Submitted' END AS ApprovalStatus, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AccountTaskTypeId, dbo.vueAccountEmployeeTimeEntryForReport.TaskStatusId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AccountPriorityId, dbo.vueAccountEmployeeTimeEntryForReport.AccountProjectMilestoneId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskType, dbo.vueAccountEmployeeTimeEntryForReport.TaskStatus, 
                      dbo.vueAccountEmployeeTimeEntryForReport.MilestoneDescription, dbo.vueAccountEmployeeTimeEntryForReport.Priority, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TotalHours, dbo.vueAccountEmployeeTimeEntryForReport.DepartmentCode, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientNick, dbo.vueAccountEmployeeTimeEntryForReport.AccountClientId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EstimatedCurrencyId, dbo.vueAccountEmployeeTimeEntryForReport.EstimatedCurrencyCode, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ApprovedOn,
				    dbo.vueAccountEmployeeTimeEntryForReport.EmployeeRate, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EmployeeRateCurrencyCode,
					 dbo.vueAccountEmployeeTimeEntryForReport.TeamLeader, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectManager, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeManager, 
                      ISNULL(dbo.vueAccountEmployeeTimeEntryForReport.EstimatedCurrencyExchangeRate, 0) AS EstimatedCurrencyExchangeRate, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCost, dbo.vueAccountEmployeeTimeEntryForReport.AccountRoleId, 
                      dbo.vueAccountEmployeeTimeEntryForReport.Role, dbo.vueAccountEmployeeTimeEntryForReport.WeekDayName, 
                      dbo.vueAccountEmployeeTimeEntryForReport.Period, dbo.vueAccountEmployeeTimeEntryForReport.Year, dbo.vueAccountEmployeeTimeEntryForReport.WeekNo, 
                      dbo.vueAccountEmployeeTimeEntryForReport.MonthNo, dbo.vueAccountEmployeeTimeEntryForReport.DayNo, 
                      CASE WHEN dbo.vueAccountEmployeeTimeEntryForReport.IsBillable = 1 THEN dbo.vueAccountEmployeeTimeEntryForReport.TotalHours ELSE 0 END AS BillableTotalHours,
                       CASE WHEN dbo.vueAccountEmployeeTimeEntryForReport.IsBillable = 0 THEN dbo.vueAccountEmployeeTimeEntryForReport.TotalHours WHEN dbo.vueAccountEmployeeTimeEntryForReport.IsBillable
                       IS NULL THEN dbo.vueAccountEmployeeTimeEntryForReport.TotalHours ELSE 0 END AS NonBillableTotalHours, 
                      CASE WHEN dbo.vueAccountEmployeeTimeEntryForReport.EmployeeRateExchangeRate > 0 THEN dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCost / dbo.vueAccountEmployeeTimeEntryForReport.EmployeeRateExchangeRate
                       ELSE 0 END AS CurrencyEmployeeCost, 
                      CASE WHEN dbo.vueAccountEmployeeTimeEntryForReport.BillingRateExchangeRate > 0 THEN dbo.vueAccountEmployeeTimeEntryForReport.Amount / dbo.vueAccountEmployeeTimeEntryForReport.BillingRateExchangeRate
                       ELSE 0 END AS CurrencyAmount, 
                      CASE WHEN dbo.vueAccountEmployeeTimeEntryForReport.EstimatedCurrencyExchangeRate > 0 THEN dbo.vueAccountEmployeeTimeEntryForReport.EstimatedCost / dbo.vueAccountEmployeeTimeEntryForReport.EstimatedCurrencyExchangeRate
                       ELSE 0 END AS CurrencyEstimatedCost, 
                      CASE WHEN dbo.vueAccountEmployeeTimeEntryForReport.BillingRateExchangeRate > 0 THEN dbo.vueAccountEmployeeTimeEntryForReport.BillingRate / dbo.vueAccountEmployeeTimeEntryForReport.BillingRateExchangeRate
                       ELSE 0 END AS CurrencyBillingRate, 
                      CASE WHEN dbo.vueAccountEmployeeTimeEntryForReport.EmployeeRateExchangeRate > 0 THEN dbo.vueAccountEmployeeTimeEntryForReport.EmployeeRate / dbo.vueAccountEmployeeTimeEntryForReport.EmployeeRateExchangeRate
                       ELSE 0 END AS CurrencyEmployeeRate, dbo.vueAccountEmployeeTimeEntryForReport.ProjectRole, dbo.vueAccountEmployeeTimeEntryForReport.ProjectType, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectDescription, dbo.vueAccountEmployeeTimeEntryForReport.TaskDescription, 
                      dbo.vueAccountEmployeeTimeEntryForReport.InvoiceNumber, dbo.vueAccountEmployeeTimeEntryForReport.InvoiceDate, 
                      dbo.vueAccountEmployeeTimeEntryForReport.AccountProjectTypeId, dbo.vueAccountEmployeeTimeEntryForReport.Billed, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientContactName, dbo.vueAccountEmployeeTimeEntryForReport.ClientDepartmentCode, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientDepartmentName, dbo.vueAccountEmployeeTimeEntryForReport.ClientDepartmentLocation, 
                      dbo.vueAccountEmployeeTimeEntryForReport.IsTimeOff, dbo.vueAccountEmployeeTimeEntryForReport.AccountWorkTypeId, 
                      CASE WHEN dbo.vueAccountEmployeeTimeEntryForReport.IsBillable = 1 THEN dbo.vueAccountEmployeeTimeEntryForReport.BillingRate * dbo.vueAccountEmployeeTimeEntryForReport.TotalHours
                       ELSE 0 END AS BillableTotalAmount, 
                      CASE WHEN dbo.vueAccountEmployeeTimeEntryForReport.IsBillable = 0 THEN dbo.vueAccountEmployeeTimeEntryForReport.BillingRate * dbo.vueAccountEmployeeTimeEntryForReport.TotalHours
                       ELSE 0 END AS NonBillableTotalAmount, dbo.vueAccountEmployeeTimeEntryForReport.ProjectStatus, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ParentTaskName, dbo.vueAccountEmployeeTimeEntryForReport.FirstName, 
                      dbo.vueAccountEmployeeTimeEntryForReport.LastName, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeType, 
                      dbo.vueAccountEmployeeTimeEntryForReport.HolidayName, 
					  
                      dbo.vueAccountEmployeeTimeEntryForReport.CustomField1, dbo.vueAccountEmployeeTimeEntryForReport.CustomField2, 
                      dbo.vueAccountEmployeeTimeEntryForReport.CustomField3, dbo.vueAccountEmployeeTimeEntryForReport.CustomField4, 
                      dbo.vueAccountEmployeeTimeEntryForReport.CustomField5, dbo.vueAccountEmployeeTimeEntryForReport.CustomField6, 
                      dbo.vueAccountEmployeeTimeEntryForReport.CustomField7, dbo.vueAccountEmployeeTimeEntryForReport.CustomField8, 
                      dbo.vueAccountEmployeeTimeEntryForReport.CustomField9, dbo.vueAccountEmployeeTimeEntryForReport.CustomField10, 
                      dbo.vueAccountEmployeeTimeEntryForReport.CustomField11, dbo.vueAccountEmployeeTimeEntryForReport.CustomField12, 
                      dbo.vueAccountEmployeeTimeEntryForReport.CustomField13, dbo.vueAccountEmployeeTimeEntryForReport.CustomField14, 
                      dbo.vueAccountEmployeeTimeEntryForReport.CustomField15, dbo.vueAccountEmployeeTimeEntryForReport.TaskStartDate, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskDeadlineDate, dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField1, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField2, dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField3, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField4, dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField5, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField6, dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField7, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField8, dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField9, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField10, dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField11, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField12, dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField13, 
                      dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField14, dbo.vueAccountEmployeeTimeEntryForReport.TaskCustomField15,
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectApprover , dbo.vueAccountEmployeeTimeEntryForReport.CurrentApprover, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField1, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField2, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField6, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField3, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField4, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField7, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField8, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField9, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField10, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField11, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField12, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField13, 
                      dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField14, dbo.vueAccountEmployeeTimeEntryForReport.EmployeeCustomField15, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField1, dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField2, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField3, dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField4, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField5, dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField6, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField7, dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField8, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField9, dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField10, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField11, dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField12, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField13, dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField14, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ClientCustomField15, vueAccountEmployeeTimeEntryForReport.TimeEntryPeriod, dbo.vueAccountEmployeeTimeEntryForReport.JobTitle, dbo.vueAccountEmployeeTimeEntryForReport.TaskEnabled, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField1, dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField2, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField3, dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField4, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField5, dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField6, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField7, dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField8, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField9, dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField10, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField11, dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField12, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField13, dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField14, 
                      dbo.vueAccountEmployeeTimeEntryForReport.ProjectCustomField15, dbo.vueAccountEmployeeTimeEntryForReport.AccountTimeOffType, dbo.vueAccountEmployeeTimeEntryForReport.AccountCostCenterId
					  ,ISNULL(dbo.vueAccountEmployeeTimeEntryForReport.Percentage, 0) AS Percentage, dbo.vueAccountEmployeeTimeEntryForReport.ProjectBillingType
FROM         dbo.vueAccountEmployeeTimeEntryForReport