
CREATE VIEW dbo.rptvueAccountProjects
AS
SELECT     dbo.vueAccountProjectsForReport.AccountProjectId, dbo.vueAccountProjectsForReport.AccountId, dbo.vueAccountProjectsForReport.AccountProjectTypeId, dbo.vueAccountProjectsForReport.AccountClientId, 
                      dbo.vueAccountProjectsForReport.ProjectBillingTypeId, dbo.vueAccountProjectsForReport.ProjectName, dbo.vueAccountProjectsForReport.ProjectDescription, dbo.vueAccountProjectsForReport.StartDate, 
                      dbo.vueAccountProjectsForReport.AccountMilestoneId, dbo.vueAccountProjectsForReport.Deadline, dbo.vueAccountProjectsForReport.LeaderEmployeeId, dbo.vueAccountProjectsForReport.ProjectManagerEmployeeId, 
                      dbo.vueAccountProjectsForReport.EstimatedTime, dbo.vueAccountProjectsForReport.EstimatedDurationUnit, dbo.vueAccountProjectsForReport.ProjectCode, dbo.vueAccountProjectsForReport.DefaultBillingRate, dbo.vueAccountProjectsForReport.IsActive, 
                      dbo.vueAccountProjectsForReport.ProjectStatusId, dbo.vueAccountProjectsForReport.AccountPriorityId, dbo.vueAccountProjectsForReport.CreatedOn, dbo.vueAccountProjectsForReport.CreatedByEmployeeId, dbo.vueAccountProjectsForReport.ModifiedOn, 
                      dbo.vueAccountProjectsForReport.ModifiedByEmployeeId, dbo.vueAccountProjectsForReport.ProjectBillingRateTypeId, dbo.vueAccountProjectsForReport.TimeSheetApprovalTypeId, dbo.vueAccountProjectsForReport.ExpenseApprovalTypeId, 
                      dbo.vueAccountProjectsForReport.IsDisabled, dbo.vueAccountProjectsForReport.IsTemplate, dbo.vueAccountProjectsForReport.IsProject, dbo.vueAccountProjectsForReport.AccountProjectTemplateId, dbo.vueAccountProjectsForReport.ClientNick, 
                      dbo.vueAccountProjectsForReport.ClientName, dbo.vueAccountProjectsForReport.ProjectType, dbo.vueAccountProjectsForReport.BillingType, dbo.vueAccountProjectsForReport.Status, dbo.vueAccountProjectsForReport.EstimatedDuration, 
                      dbo.vueAccountProjectsForReport.AccountClientContactId, dbo.vueAccountProjectsForReport.AccountClientDepartmentId, dbo.vueAccountProjectsForReport.ClientDepartmentCode, dbo.vueAccountProjectsForReport.ClientDepartmentName, 
                      dbo.vueAccountProjectsForReport.ClientDepartmentLocation, dbo.vueAccountProjectsForReport.ExpenseApprovalTypeName, dbo.vueAccountProjectsForReport.TimesheetApprovalTypeName, dbo.vueAccountProjectsForReport.ClientContactName, 
                      dbo.vueAccountProjectsForReport.TeamLead, dbo.vueAccountProjectsForReport.ProjectManager, dbo.vueAccountProjectsForReport.ProjectBillingRateType, dbo.vueAccountProjectsForReport.BillableTotalHours, 
                      dbo.vueAccountProjectsForReport.NonBillableTotalHours, ISNULL(dbo.vueAccountProjectsForReport.TotalEmployeeCost, 0) AS TotalEmployeeCost, SUM(dbo.vueAccountProjectTask.EstimatedCost) AS TotalTaskEstimatedCost, SUM(dbo.vueAccountProjectTask.EstimatedTimeSpent) 
                      AS TotalTaskEstimatedHours, dbo.vueAccountProjectsForReport.TotalHours, dbo.vueAccountProjectsForReport.BillableTimeAmount, dbo.vueAccountProjectsForReport.NonBillableTimeAmount, dbo.vueAccountProjectsForReport.TotalTimeAmount, 
                      dbo.vueAccountProjectsForReport.CustomField1, dbo.vueAccountProjectsForReport.CustomField2, dbo.vueAccountProjectsForReport.CustomField3, dbo.vueAccountProjectsForReport.CustomField4, dbo.vueAccountProjectsForReport.CustomField5, dbo.vueAccountProjectsForReport.CustomField6, 
                      dbo.vueAccountProjectsForReport.CustomField7, dbo.vueAccountProjectsForReport.CustomField8, dbo.vueAccountProjectsForReport.CustomField9, dbo.vueAccountProjectsForReport.CustomField10, dbo.vueAccountProjectsForReport.CustomField11, dbo.vueAccountProjectsForReport.CustomField12, 
                      dbo.vueAccountProjectsForReport.CustomField13, dbo.vueAccountProjectsForReport.CustomField14, dbo.vueAccountProjectsForReport.CustomField15, dbo.vueAccountProjectsForReport.ProjectEstimatedCost
FROM         dbo.vueAccountProjectsForReport LEFT OUTER JOIN
                      dbo.vueAccountProjectTask ON dbo.vueAccountProjectsForReport.AccountProjectId = dbo.vueAccountProjectTask.AccountProjectId
GROUP BY dbo.vueAccountProjectsForReport.AccountProjectId, dbo.vueAccountProjectsForReport.AccountId, dbo.vueAccountProjectsForReport.AccountProjectTypeId, dbo.vueAccountProjectsForReport.AccountClientId, 
                      dbo.vueAccountProjectsForReport.ProjectBillingTypeId, dbo.vueAccountProjectsForReport.ProjectName, dbo.vueAccountProjectsForReport.ProjectDescription, dbo.vueAccountProjectsForReport.StartDate, 
                      dbo.vueAccountProjectsForReport.AccountMilestoneId, dbo.vueAccountProjectsForReport.Deadline, dbo.vueAccountProjectsForReport.LeaderEmployeeId, dbo.vueAccountProjectsForReport.ProjectManagerEmployeeId, 
                      dbo.vueAccountProjectsForReport.EstimatedTime, dbo.vueAccountProjectsForReport.EstimatedDurationUnit, dbo.vueAccountProjectsForReport.ProjectCode, dbo.vueAccountProjectsForReport.IsActive, dbo.vueAccountProjectsForReport.ProjectStatusId, 
                      dbo.vueAccountProjectsForReport.DefaultBillingRate, dbo.vueAccountProjectsForReport.AccountPriorityId, dbo.vueAccountProjectsForReport.CreatedOn, dbo.vueAccountProjectsForReport.CreatedByEmployeeId, dbo.vueAccountProjectsForReport.ModifiedOn, 
                      dbo.vueAccountProjectsForReport.ModifiedByEmployeeId, dbo.vueAccountProjectsForReport.ProjectBillingRateTypeId, dbo.vueAccountProjectsForReport.TimeSheetApprovalTypeId, dbo.vueAccountProjectsForReport.ExpenseApprovalTypeId, 
                      dbo.vueAccountProjectsForReport.IsDisabled, dbo.vueAccountProjectsForReport.IsTemplate, dbo.vueAccountProjectsForReport.IsProject, dbo.vueAccountProjectsForReport.AccountProjectTemplateId, dbo.vueAccountProjectsForReport.ClientNick, 
                      dbo.vueAccountProjectsForReport.ClientName, dbo.vueAccountProjectsForReport.ProjectType, dbo.vueAccountProjectsForReport.BillingType, dbo.vueAccountProjectsForReport.Status, dbo.vueAccountProjectsForReport.EstimatedDuration, 
                      dbo.vueAccountProjectsForReport.AccountClientContactId, dbo.vueAccountProjectsForReport.AccountClientDepartmentId, dbo.vueAccountProjectsForReport.ClientDepartmentCode, dbo.vueAccountProjectsForReport.ClientDepartmentName, 
                      dbo.vueAccountProjectsForReport.ClientDepartmentLocation, dbo.vueAccountProjectsForReport.ExpenseApprovalTypeName, dbo.vueAccountProjectsForReport.TimesheetApprovalTypeName, dbo.vueAccountProjectsForReport.ClientContactName, 
                      dbo.vueAccountProjectsForReport.TeamLead, dbo.vueAccountProjectsForReport.ProjectManager, dbo.vueAccountProjectsForReport.ProjectBillingRateType, dbo.vueAccountProjectsForReport.BillableTotalHours, 
                      dbo.vueAccountProjectsForReport.NonBillableTotalHours, dbo.vueAccountProjectsForReport.TotalEmployeeCost, dbo.vueAccountProjectsForReport.TotalHours, dbo.vueAccountProjectsForReport.BillableTimeAmount, 
                      dbo.vueAccountProjectsForReport.NonBillableTimeAmount, dbo.vueAccountProjectsForReport.TotalTimeAmount, dbo.vueAccountProjectsForReport.CustomField1, dbo.vueAccountProjectsForReport.CustomField2, dbo.vueAccountProjectsForReport.CustomField3, 
                      dbo.vueAccountProjectsForReport.CustomField4, dbo.vueAccountProjectsForReport.CustomField5, dbo.vueAccountProjectsForReport.CustomField6, 
                      dbo.vueAccountProjectsForReport.CustomField7, dbo.vueAccountProjectsForReport.CustomField8, dbo.vueAccountProjectsForReport.CustomField9, 
                      dbo.vueAccountProjectsForReport.CustomField10, dbo.vueAccountProjectsForReport.CustomField11, dbo.vueAccountProjectsForReport.CustomField12, 
                      dbo.vueAccountProjectsForReport.CustomField13, dbo.vueAccountProjectsForReport.CustomField14, dbo.vueAccountProjectsForReport.CustomField15, 
                      dbo.vueAccountProjectsForReport.ProjectEstimatedCost