
CREATE VIEW dbo.vueAccountProjectsForReport
AS
SELECT     dbo.vueAccountProjectsOnlyForReport.AccountProjectId, dbo.vueAccountProjectsOnlyForReport.AccountId, dbo.vueAccountProjectsOnlyForReport.AccountProjectTypeId, dbo.vueAccountProjectsOnlyForReport.AccountClientId, 
                      dbo.vueAccountProjectsOnlyForReport.ProjectBillingTypeId, dbo.vueAccountProjectsOnlyForReport.ProjectName, dbo.vueAccountProjectsOnlyForReport.ProjectDescription, dbo.vueAccountProjectsOnlyForReport.StartDate, 
                      dbo.vueAccountProjectsOnlyForReport.AccountMilestoneId, dbo.vueAccountProjectsOnlyForReport.Deadline, dbo.vueAccountProjectsOnlyForReport.LeaderEmployeeId, dbo.vueAccountProjectsOnlyForReport.ProjectManagerEmployeeId, 
                      dbo.vueAccountProjectsOnlyForReport.EstimatedTime, dbo.vueAccountProjectsOnlyForReport.EstimatedDurationUnit, 
                      ISNULL(dbo.vueAccountProjectsOnlyForReport.ProjectCode, N'') AS ProjectCode, dbo.vueAccountProjectsOnlyForReport.DefaultBillingRate, 
                      dbo.vueAccountProjectsOnlyForReport.IsActive, dbo.vueAccountProjectsOnlyForReport.ProjectStatusId, dbo.vueAccountProjectsOnlyForReport.AccountPriorityId, dbo.vueAccountProjectsOnlyForReport.CreatedOn, 
                      dbo.vueAccountProjectsOnlyForReport.CreatedByEmployeeId, dbo.vueAccountProjectsOnlyForReport.ModifiedOn, dbo.vueAccountProjectsOnlyForReport.ModifiedByEmployeeId, dbo.vueAccountProjectsOnlyForReport.ProjectBillingRateTypeId, 
                      dbo.vueAccountProjectsOnlyForReport.TimeSheetApprovalTypeId, dbo.vueAccountProjectsOnlyForReport.ExpenseApprovalTypeId, dbo.vueAccountProjectsOnlyForReport.IsDisabled, dbo.vueAccountProjectsOnlyForReport.IsTemplate, dbo.vueAccountProjectsOnlyForReport.IsProject, 
                      dbo.vueAccountProjectsOnlyForReport.AccountProjectTemplateId, ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientNick, N'') AS ClientNick, dbo.vueAccountProjectsOnlyForReport.ClientName, dbo.vueAccountProjectsOnlyForReport.ProjectType, 
                      dbo.vueAccountProjectsOnlyForReport.BillingType, dbo.vueAccountProjectsOnlyForReport.Status, dbo.vueAccountProjectsOnlyForReport.EstimatedDuration + ' - ' + dbo.vueAccountProjectsOnlyForReport.EstimatedDurationUnit AS EstimatedDuration, 
                      dbo.vueAccountProjectsOnlyForReport.AccountClientContactId, dbo.vueAccountProjectsOnlyForReport.AccountClientDepartmentId, ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientDepartmentCode, N'') AS ClientDepartmentCode, 
                      ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientDepartmentName, N'') AS ClientDepartmentName, ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientDepartmentLocation, N'') AS ClientDepartmentLocation, ISNULL(dbo.vueAccountProjectsOnlyForReport.ExpenseApprovalTypeName, N'') AS ExpenseApprovalTypeName, 
                      ISNULL(dbo.vueAccountProjectsOnlyForReport.TimesheetApprovalTypeName, N'') AS TimesheetApprovalTypeName, ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientContactName, N'') AS ClientContactName, dbo.vueAccountProjectsOnlyForReport.TeamLead, 
                      dbo.vueAccountProjectsOnlyForReport.ProjectManager, dbo.vueAccountProjectsOnlyForReport.ProjectBillingRateType, ISNULL(SUM(dbo.rptvueAccountEmployeeTimeEntryForProjectReport.BillableTotalHours), 0) AS BillableTotalHours, 
                      ISNULL(SUM(dbo.rptvueAccountEmployeeTimeEntryForProjectReport.NonBillableTotalHours), 0) AS NonBillableTotalHours, SUM(dbo.rptvueAccountEmployeeTimeEntryForProjectReport.EmployeeCost) AS TotalEmployeeCost, 
                      ISNULL(SUM(dbo.rptvueAccountEmployeeTimeEntryForProjectReport.Amount), 0) AS TotalTimeAmount, ISNULL(SUM(dbo.rptvueAccountEmployeeTimeEntryForProjectReport.TotalHours), 0) AS TotalHours, 
                      ISNULL(SUM(dbo.rptvueAccountEmployeeTimeEntryForProjectReport.BillableTotalAmount), 0) AS BillableTimeAmount, ISNULL(SUM(dbo.rptvueAccountEmployeeTimeEntryForProjectReport.NonBillableTotalAmount), 0) AS NonBillableTimeAmount, 
                      dbo.vueAccountProjectsOnlyForReport.CustomField1, dbo.vueAccountProjectsOnlyForReport.CustomField2, dbo.vueAccountProjectsOnlyForReport.CustomField3, dbo.vueAccountProjectsOnlyForReport.CustomField4, 
                      dbo.vueAccountProjectsOnlyForReport.CustomField5, dbo.vueAccountProjectsOnlyForReport.CustomField6, dbo.vueAccountProjectsOnlyForReport.CustomField7, dbo.vueAccountProjectsOnlyForReport.CustomField8, 
                      dbo.vueAccountProjectsOnlyForReport.CustomField9, dbo.vueAccountProjectsOnlyForReport.CustomField10, dbo.vueAccountProjectsOnlyForReport.CustomField11, dbo.vueAccountProjectsOnlyForReport.CustomField12, 
                      dbo.vueAccountProjectsOnlyForReport.CustomField13, dbo.vueAccountProjectsOnlyForReport.CustomField14, dbo.vueAccountProjectsOnlyForReport.CustomField15, dbo.vueAccountProjectsOnlyForReport.ProjectEstimatedCost
FROM         dbo.vueAccountProjectsOnlyForReport LEFT OUTER JOIN
                      dbo.rptvueAccountEmployeeTimeEntryForProjectReport ON 
                      dbo.vueAccountProjectsOnlyForReport.AccountProjectId = dbo.rptvueAccountEmployeeTimeEntryForProjectReport.AccountProjectId 
GROUP BY dbo.vueAccountProjectsOnlyForReport.AccountProjectId, dbo.vueAccountProjectsOnlyForReport.AccountId, dbo.vueAccountProjectsOnlyForReport.AccountProjectTypeId, dbo.vueAccountProjectsOnlyForReport.AccountClientId, 
                      dbo.vueAccountProjectsOnlyForReport.ProjectBillingTypeId, dbo.vueAccountProjectsOnlyForReport.ProjectName, dbo.vueAccountProjectsOnlyForReport.ProjectDescription, dbo.vueAccountProjectsOnlyForReport.StartDate, 
                      dbo.vueAccountProjectsOnlyForReport.AccountMilestoneId, dbo.vueAccountProjectsOnlyForReport.Deadline, dbo.vueAccountProjectsOnlyForReport.LeaderEmployeeId, dbo.vueAccountProjectsOnlyForReport.ProjectManagerEmployeeId, 
                      dbo.vueAccountProjectsOnlyForReport.EstimatedTime, dbo.vueAccountProjectsOnlyForReport.EstimatedDurationUnit, ISNULL(dbo.vueAccountProjectsOnlyForReport.ProjectCode, N''), dbo.vueAccountProjectsOnlyForReport.DefaultBillingRate, 
                      dbo.vueAccountProjectsOnlyForReport.IsActive, dbo.vueAccountProjectsOnlyForReport.ProjectStatusId, dbo.vueAccountProjectsOnlyForReport.AccountPriorityId, dbo.vueAccountProjectsOnlyForReport.CreatedOn, 
                      dbo.vueAccountProjectsOnlyForReport.CreatedByEmployeeId, dbo.vueAccountProjectsOnlyForReport.ModifiedOn, dbo.vueAccountProjectsOnlyForReport.ModifiedByEmployeeId, dbo.vueAccountProjectsOnlyForReport.ProjectBillingRateTypeId, 
                      dbo.vueAccountProjectsOnlyForReport.TimeSheetApprovalTypeId, dbo.vueAccountProjectsOnlyForReport.ExpenseApprovalTypeId, dbo.vueAccountProjectsOnlyForReport.IsDisabled, dbo.vueAccountProjectsOnlyForReport.IsTemplate, dbo.vueAccountProjectsOnlyForReport.IsProject, 
                      dbo.vueAccountProjectsOnlyForReport.AccountProjectTemplateId, ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientNick, N''), dbo.vueAccountProjectsOnlyForReport.ClientName, dbo.vueAccountProjectsOnlyForReport.ProjectType, dbo.vueAccountProjectsOnlyForReport.BillingType, dbo.vueAccountProjectsOnlyForReport.Status, 
                      dbo.vueAccountProjectsOnlyForReport.EstimatedDuration + ' - ' + dbo.vueAccountProjectsOnlyForReport.EstimatedDurationUnit, dbo.vueAccountProjectsOnlyForReport.AccountClientContactId, dbo.vueAccountProjectsOnlyForReport.AccountClientDepartmentId, 
                      ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientDepartmentCode, N''), ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientDepartmentName, N''), 
                      ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientDepartmentLocation, N''), ISNULL(dbo.vueAccountProjectsOnlyForReport.ExpenseApprovalTypeName, N''), 
                      ISNULL(dbo.vueAccountProjectsOnlyForReport.TimesheetApprovalTypeName, N''), ISNULL(dbo.vueAccountProjectsOnlyForReport.ClientContactName, N''), dbo.vueAccountProjectsOnlyForReport.TeamLead, dbo.vueAccountProjectsOnlyForReport.ProjectManager, 
                      dbo.vueAccountProjectsOnlyForReport.ProjectBillingRateType, dbo.vueAccountProjectsOnlyForReport.CustomField1, dbo.vueAccountProjectsOnlyForReport.CustomField2, dbo.vueAccountProjectsOnlyForReport.CustomField3, 
                      dbo.vueAccountProjectsOnlyForReport.CustomField4, dbo.vueAccountProjectsOnlyForReport.CustomField5, dbo.vueAccountProjectsOnlyForReport.CustomField6, dbo.vueAccountProjectsOnlyForReport.CustomField7, 
                      dbo.vueAccountProjectsOnlyForReport.CustomField8, dbo.vueAccountProjectsOnlyForReport.CustomField9, dbo.vueAccountProjectsOnlyForReport.CustomField10, dbo.vueAccountProjectsOnlyForReport.CustomField11, 
                      dbo.vueAccountProjectsOnlyForReport.CustomField12, dbo.vueAccountProjectsOnlyForReport.CustomField13, dbo.vueAccountProjectsOnlyForReport.CustomField14, dbo.vueAccountProjectsOnlyForReport.CustomField15, 
                      dbo.vueAccountProjectsOnlyForReport.ProjectEstimatedCost