
Create PROCEDURE [dbo].[sp_xpAllocationDataSetAP] 
	-- Add the parameters for the stored procedure here
	@pYear varchar(4), 
	@pMonth varchar(10)
AS
begin
IF @pMonth = '*' 

	begin
		SELECT ROUND(CAST( TTP AS DECIMAL(5,2))/CAST( TTM AS DECIMAL(5,2)),4) as PCT_ALLOC, A._PROJECT_DESCRIPTION AS DIVISION, A._PROJECT_CODE as PROJECT_CODE, A._EMPLOYEE_CODE as EMPLOYEE_CODE, A._MONTH_NR as MONTH_NR, A._MONTH
		FROM
		(SELECT _EMPLOYEE_CODE, _PROJECT_CODE, DATEPART(month, _DATE) as _MONTH, _MONTH_NR , _PROJECT_DESCRIPTION, SUM(_TOTAL_TIME) TTP
		FROM VXP_DETAILMONTHALLOCATION DWA
		WHERE 
		CONVERT(VARCHAR(4), datename(year,_DATE)) = CONVERT(VARCHAR(4),@pYear)
		AND UPPER(_PROJECT_CODE) <> 'XP.ABSENCE'
		AND UPPER(_TASK_CODE) NOT LIKE '%EXTRA%'
		AND _APPROVED = 1
		AND _SUBMITTED = 1
		GROUP BY _EMPLOYEE_CODE, _PROJECT_CODE, DATEPART(month, _DATE), _MONTH_NR, _PROJECT_DESCRIPTION) A,
		(SELECT _EMPLOYEE_CODE, DATEPART(month, _DATE) as _MONTH,  _MONTH_NR,SUM(_TOTAL_TIME) TTM
		FROM VXP_DETAILMONTHALLOCATION DWA
		WHERE 
		CONVERT(VARCHAR(4), datename(year,_DATE)) = CONVERT(VARCHAR(4),@pYear)
		AND UPPER(_PROJECT_CODE) <> 'XP.ABSENCE'
		AND UPPER(_TASK_CODE) NOT LIKE '%EXTRA%'
		GROUP BY _EMPLOYEE_CODE, DATEPART(month, _DATE),_MONTH_NR) B
		WHERE A._MONTH_NR = B._MONTH_NR
		AND B.TTM > 0
		AND A._MONTH=B._MONTH
		AND A._EMPLOYEE_CODE = B._EMPLOYEE_CODE
		ORDER BY EMPLOYEE_CODE, _MONTH, PROJECT_CODE
	end
else
	begin
		SELECT ROUND(CAST( TTP AS DECIMAL(5,2))/CAST( TTM AS DECIMAL(5,2)),4) as PCT_ALLOC, A._PROJECT_DESCRIPTION AS DIVISION, A._PROJECT_CODE as PROJECT_CODE, A._EMPLOYEE_CODE as EMPLOYEE_CODE, A._MONTH_NR as MONTH_NR, A._MONTH
		FROM
		(SELECT _EMPLOYEE_CODE, _PROJECT_CODE, DATEPART(month, _DATE) as _MONTH, _MONTH_NR , _PROJECT_DESCRIPTION, SUM(_TOTAL_TIME) TTP
		FROM VXP_DETAILMONTHALLOCATION DWA
		WHERE CONVERT(VARCHAR(7), _DATE, 120) = CONVERT(VARCHAR(7),CONVERT(datetime,convert(varchar,@pYear)+'-'+convert(varchar,@pMonth)+'-01',120),120)
		AND UPPER(_PROJECT_CODE) <> 'XP.ABSENCE'
		AND UPPER(_TASK_CODE) NOT LIKE '%EXTRA%'
		AND _APPROVED = 1
		AND _SUBMITTED = 1
		GROUP BY _EMPLOYEE_CODE, _PROJECT_CODE, DATEPART(month, _DATE), _MONTH_NR, _PROJECT_DESCRIPTION) A,
		(SELECT _EMPLOYEE_CODE, DATEPART(month, _DATE) as _MONTH,  _MONTH_NR,SUM(_TOTAL_TIME) TTM
		FROM VXP_DETAILMONTHALLOCATION DWA
		WHERE CONVERT(VARCHAR(7), _DATE, 120) = CONVERT(VARCHAR(7),CONVERT(datetime,convert(varchar,@pYear)+'-'+convert(varchar,@pMonth)+'-01',120),120)
		AND UPPER(_PROJECT_CODE) <> 'XP.ABSENCE'
		AND UPPER(_TASK_CODE) NOT LIKE '%EXTRA%'
		GROUP BY _EMPLOYEE_CODE, DATEPART(month, _DATE),_MONTH_NR) B
		WHERE A._MONTH_NR = B._MONTH_NR
		AND B.TTM > 0
		AND A._MONTH=B._MONTH
		AND A._EMPLOYEE_CODE = B._EMPLOYEE_CODE
		ORDER BY EMPLOYEE_CODE, _MONTH, PROJECT_CODE

	end



END